### ISSUE TITLE
How to support multiple path revalidations at once?

### ISSUE THREAD

**Issue by leerob** [leerob/on-demand-isr#131]
Feedback from Reddit: It seems right now `unstable_revalidate` can only take a single string suggesting one path at a time. I would love for this feature to accept an array of strings – or better yet – maybe a regex so I can rebuild entire branches of a sitemap.

**Comment by tiacop** [comment]
Something like cache-tags would be awesome:
https://developers.cloudflare.com/cache/how-to/purge-cache#cache-tags-enterprise-only
