### ISSUE TITLE
On 12.1 it did not work at first

### ISSUE THREAD

**Issue by amorenopbsc** [leerob/on-demand-isr#1467]
When I read the documentation it was clear, then I watched a video from vercel team, and I added the code, and totally forgot I had to include the feature flag to enable it, so it never worked back then. I hope with 12.2 works as I was expecting it.

**Comment by leerob** [comment]
Hey! There wasn't a feature flag needed to use on-demand ISR. You did need the `unstable_` prefix at first. Are you thinking of a different feature?
