### ISSUE TITLE
works in development but fails on production build

### ISSUE THREAD

**Issue by gholevas** [leerob/on-demand-isr#154]
I posted my code below. I removed the secret validation so that any post request to the API endpoint "/api/revalidate" should revalidate the page slug that is sent in the post body.
The API endpoint returns {revalidated: true} in development, but {error:'Revalidation failed'} in a production build

```
export default async function handler(req, res) {
  try {
    await res.unstable_revalidate(`/${req.body.slug}`)
    return res.json({ revalidated: true })
  } catch (err) {
    console.log('err', err)
    res.status(500).json({ error: 'Revalidation failed' })
  }
}
```

**Comment by leerob** [comment]
Could you share a repo with a reproduction as well as the deployed URL?
