### ISSUE TITLE
Real Issue: After clicking an issue and click back to home, it shows different hours by default.

### ISSUE THREAD

**Issue by surjithctly** [leerob/on-demand-isr#225]
Great feature but there is an issue. 

@leerob After clicking an issue link and then clicking back, it shows different items by default (not latest). See GIF below. 

![CleanShot 2022-02-18 at 13 49 00](https://user-images.githubusercontent.com/1884712/154644785-83b47e73-2e75-4aff-a208-772326b3b388.gif)

**Comment by sunnysonx** [comment]
Indeed. The same happens to me, and it displays the same issues as in your screenshot.

**Comment by leerob** [comment]
Fixing, thank you!
