### ISSUE TITLE
Will this Work with international Routing / i18n

### ISSUE THREAD

**Issue by jan-victor** [leerob/on-demand-isr#441]
When having
`  i18n: {
    locales: ['x-default', 'de'],
    defaultLocale: 'x-default',
    localeDetection: false,
  },`
  
in your next.config.js
Will this still work?

**Comment by leerob** [comment]
Yes, you would need to be explicit about the URLs you want to revalidte. e.g. you would need to call `unstable_revalidate` for each locale.
