### ISSUE TITLE
missing npx in the command

### ISSUE THREAD

**Issue by usabe** [leerob/on-demand-isr#672]
Was checking through the nextjs docs. Found some command missing "npx", like "next ...". Not big deal, but could be better in the detail.

**Comment by leerob** [comment]
Where at specifically?

**Comment by usabe** [comment]
Thanks for the reply. Actually I was just writing something to test the on-demand isr function: https://on-demand-isr.vercel.app/ . Don't want to just put some "test, test, bla, bla, bla". Didn't expect someone will really check it :)  

E.g., on this page: https://nextjs.org/docs/api-reference/cli . But seems it still works without npx. It's just sometime with npx sometimes without npx may cause some confusion for new learners.
